CREATE TABLE [dbo].[Polls]
(
	[PollId] INT NOT NULL PRIMARY KEY IDENTITY (1,1), 
    [PollType] NVARCHAR(50) NOT NULL, 
    [PollQuestion] NVARCHAR(100) NOT NULL, 
    [PostId] INT NOT NULL, 
    CONSTRAINT [FK_Polls_ToPosts] FOREIGN KEY ([PostId]) REFERENCES [Posts]([PostId]) ON DELETE CASCADE
)
